In [1]:
# 파이썬 데이터분석 라이브러리 numpy
import numpy as np

In [12]:
# 1차원 list의 array
data1 = [6,7.5,8,0,1]

In [13]:
# data1을 인자로 가진 새로운 array 생성  
arr1 = np.array(data1)

In [15]:
# 행렬과 다르고 크기가 5인 벡터와 비슷
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
# 크기, 배열이면 배열 원소들의 개수 / 크기 정보를 track하는 것이 매우 중요
arr1.shape

(5,)

In [17]:
# 2차원 리스트 array  / 2*4, 2행 4열의 array
data2 = [ [1,2,3,4],
        [5,6,7,8]]

In [9]:
arr2 = np.array(data2)

In [10]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.shape

(2, 4)

In [22]:
# 성분이 0으로만 구성된 array 만들기 / ()안에는 array의 크기
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
# 성분이 1로만 구성되어있는 array 생성
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
# python 의 range함수와 비슷, 0부터 ()-1 까지
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
# array의 데이터형 
arr1.dtype
# array1에는 7.5가 들어가있기 때문에 float형으로 변환됨

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [32]:
# data type과 지정한대로 array 만들기
arr = np.array([1,2,3,4,5], dtype=np.int64)

In [33]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [34]:
arr.dtype

dtype('int64')

In [36]:
# 기존 arr이름의 array에
데이터 타입 변환
float_arr = arr.astype(np.float64)

In [37]:
float_arr

array([1., 2., 3., 4., 5.])

In [38]:
float_arr.dtype

dtype('float64')