In [1]:
import numpy as np

In [3]:
# file 읽기 / numpy에 array 형태로 메모리에 저장됨
data = np.loadtxt("C:/Users/SSO/python_data/data\movielens_1m/ratings.dat", delimiter="::", dtype=np.int64)

In [5]:
# data에 저장된 맨 앞 5개 정도 미리 확인
data[:5, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [7]:
# data를 잘 읽어들였나 확인
data.shape

(1000209, 4)

In [10]:
# 전체 평균 평점 계산하기 / data는 전체에서 rating이 위치한 2열만 추출 / 
mean_rating_total = data[:,2].mean()

In [12]:
# 전체 평균 평점
mean_rating_total

3.581564453029317

In [13]:
# 각사용자별 평균 평점 계산 
# 중복 되있을 user id를 한번씩 뽑기 위해서는 unique한 id들 뽑기 함수 사용 / user id는 첫번째 열에 위치
user_ids = np.unique(data[:,0])

In [14]:
user_ids[:5]

array([1, 2, 3, 4, 5], dtype=int64)

In [15]:
user_ids.shape

(6040,)

In [21]:
# 빈 list 만들기
mean_rating_by_user_list = []
# for문 활용해 같은 user id로 boolean 생성해 행을 다 추출하고 그 때 2번째 열의 rating의 평균을 구해준다 
for user_id in user_ids:
    data_for_user = data[data[:, 0] == user_id, :] # user_id 와 data의 0번째 열에 위치한 값이 같을 때 행들을 죄다 추출
    mean_rating_for_user = data_for_user[:,2].mean() # 추출된 data_for_user행들의 2번째인 rating값의 평균을 구한다
    mean_rating_by_user_list.append([user_id, mean_rating_for_user]) # []2개의 성분로 구성된 list를 만들어 준다

In [34]:
# 잘 되었나 확인  / user_id , 평균 평점
mean_rating_by_user_list[:5]

array([[1.       , 4.188679 ],
       [2.       , 3.7131784],
       [3.       , 3.9019608],
       [4.       , 4.1904764],
       [5.       , 3.1464646]], dtype=float32)

In [45]:
# array 함수 사용, 관리하기 쉽게 2차원 list를  array함수를 사용해 array로 변환
mean_rating_by_user_array = np.array(mean_rating_by_user_list, dtype=np.float32)

In [46]:
mean_rating_by_user_array[:5]

array([[1.       , 4.188679 ],
       [2.       , 3.7131784],
       [3.       , 3.9019608],
       [4.       , 4.1904764],
       [5.       , 3.1464646]], dtype=float32)

In [47]:
# 2차원 array 확인
mean_rating_by_user_array.shape

(6040, 2)

In [50]:
# 외부 파일로 사용하기 위해 저장 ("파일이름", 저장에 사용할 array, fmt형태, 구분자)
np.savetxt("mean_rating_by_user.csv", mean_rating_by_user_array, fmt="%.3f", delimiter=",")