In [1]:
# numpy 패키지 import
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# sqrt array 각 성분의 제곱근 계산
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [7]:
x = np.random.randn(8)
y = np.random.randn(8)

In [8]:
x

array([-1.99724279,  0.50200251, -1.14540942, -0.13245187,  0.58020072,
       -0.78884422,  0.18154626, -0.2283348 ])

In [9]:
y

array([ 0.73124766, -0.84618242, -0.36286469,  1.19752526,  0.53799361,
       -1.19961176,  0.43911639,  1.13728984])

In [11]:
# 두 array 비교 후 각 위치에서 값이 더 큰 성분을 선택해 새로운 array로 제시
np.maximum(x,y)

array([ 0.73124766,  0.50200251, -0.36286469,  1.19752526,  0.58020072,
       -0.78884422,  0.43911639,  1.13728984])

In [12]:
z = np.random.randn(2,4)

In [13]:
z

array([[-1.18422527,  0.62720407,  0.71641335,  1.05670313],
       [ 0.93927388, -1.23495188,  0.04416652,  0.799491  ]])

In [14]:
# 통계함수
arr = np.random.randn(5,4)

In [15]:
arr

array([[-1.79280282, -0.11825352, -1.46277423,  0.53416345],
       [-0.72600654,  1.61121593, -1.40355345,  0.29949921],
       [-0.02321552,  0.22115727,  0.43435528, -1.4428517 ],
       [ 0.29037265,  1.45451148, -0.68891245,  0.78027954],
       [-0.50760602, -0.95051852, -1.29167203, -0.38647852]])

In [16]:
# array 전체 성분의 합
arr.sum()

-5.169090502837454

In [18]:
# 전체 성분의 평균
arr.mean()

-0.2584545251418727

In [23]:
# 각 열의 합 / 기존의 행 방향으로 계산
arr.sum(axis=0)

array([-2.75925826,  2.21811265, -4.41255688, -0.21538802])

In [24]:
# 각 행의 합 / 기존의 열 방향으로 계산
arr.sum(axis=1)

array([-2.83966711, -0.21884485, -0.81055467,  1.83625122, -3.13627509])

In [26]:
arr > 0  # 불리언을 통해 마스크 생성

array([[False, False, False,  True],
       [False,  True, False,  True],
       [False,  True,  True, False],
       [ True,  True, False,  True],
       [False, False, False, False]])

In [31]:
# True 1 / False 0 으로 간주하여 계산 / 조건 만족하는 데이터의 총 개수를 산출
(arr > 0).sum()

8

In [32]:
arr = np.random.randn(8)

In [33]:
arr

array([-0.59753093,  0.9391057 ,  3.15865767,  0.32955598,  0.87609356,
       -0.14775112, -1.12590323, -0.26438528])

In [36]:
# 값이 작은 것 부터 오름차순 정렬
np.sort(arr)

array([-1.12590323, -0.59753093, -0.26438528, -0.14775112,  0.32955598,
        0.87609356,  0.9391057 ,  3.15865767])

In [38]:
# 값이 큰 것부터 내림차순 / 꼼수
np.sort(arr)[::-1]

array([ 3.15865767,  0.9391057 ,  0.87609356,  0.32955598, -0.14775112,
       -0.26438528, -0.59753093, -1.12590323])

In [46]:
# 2차원 배열 생성
arr = np.random.randn(6,3)

In [47]:
arr

array([[-0.89564776,  0.31636765,  0.13007334],
       [-0.06889746,  0.56621981,  1.88776496],
       [-0.61481903, -1.19226451, -1.4758791 ],
       [ 0.4009255 ,  0.40136233, -0.42749721],
       [ 0.48114553, -0.04300665,  0.51521955],
       [-0.32621408,  0.34843301,  0.32019289]])

In [48]:
# 행 방향 오름차순 정렬 / 열에서 오름차순( 작은 것 부터 큰 것 ) 정렬
np.sort(arr, axis=0)

array([[-0.89564776, -1.19226451, -1.4758791 ],
       [-0.61481903, -0.04300665, -0.42749721],
       [-0.32621408,  0.31636765,  0.13007334],
       [-0.06889746,  0.34843301,  0.32019289],
       [ 0.4009255 ,  0.40136233,  0.51521955],
       [ 0.48114553,  0.56621981,  1.88776496]])

In [52]:
# 크기가 150인 arr
large_arr = np.random.randn(150)

In [53]:
large_arr

array([ 0.90013388, -0.30012931, -0.4974812 ,  0.3595833 ,  1.70058955,
        0.22068635,  0.40278731, -0.06432429,  0.0082027 ,  0.2170367 ,
        0.24987989, -1.0086518 , -0.03123168,  0.34426616, -0.65349319,
       -0.61754454, -0.13830983, -0.46627162, -0.90603739,  1.53184004,
        1.58276422,  1.10200396, -0.17041006,  0.90502927,  0.00679818,
       -0.2295756 , -0.94470919,  1.08052251,  0.3337283 , -1.65078425,
       -0.23489026,  0.3135538 , -1.03011163,  1.00850071,  1.93849673,
       -0.69675876, -0.70089904, -0.66719383,  0.77854551, -0.0706922 ,
        0.66544149,  0.52149126, -1.46480422, -0.42224102,  0.9644034 ,
        0.88852064,  1.57787851,  0.94999989,  0.76370848,  1.84641596,
        0.80324404, -0.01215137, -0.46153886,  0.52942648, -0.77331503,
        0.63198979, -1.45711703, -1.52320519, -0.3758528 ,  0.1839649 ,
       -2.51628663, -0.04647057, -1.19789698,  0.34565656,  0.68284274,
       -0.88353444, -1.56268514, -1.31208457,  1.49417595,  1.44

In [56]:
# 내림차순 정렬
np.sort(large_arr)[::-1]

array([ 2.44706792,  2.29109998,  2.27753039,  2.09575345,  1.93849673,
        1.84641596,  1.75725021,  1.70058955,  1.68432868,  1.61791305,
        1.58276422,  1.57787851,  1.53184004,  1.49417595,  1.44806038,
        1.34979835,  1.25121944,  1.24151107,  1.14913047,  1.13864661,
        1.11780198,  1.10200396,  1.08052251,  1.04244401,  1.00850071,
        0.9644034 ,  0.95485047,  0.94999989,  0.93221038,  0.90502927,
        0.90013388,  0.88852064,  0.87216349,  0.8602168 ,  0.85604303,
        0.80567188,  0.80324404,  0.77854551,  0.76370848,  0.71856175,
        0.69455156,  0.68284274,  0.67147081,  0.66544149,  0.65759557,
        0.64092258,  0.63198979,  0.61718272,  0.53405024,  0.52942648,
        0.52149126,  0.48699982,  0.42705765,  0.40278731,  0.3595833 ,
        0.34565656,  0.34426616,  0.3337283 ,  0.3135538 ,  0.29723007,
        0.27101101,  0.26229489,  0.24987989,  0.23623456,  0.22068635,
        0.2170367 ,  0.18646731,  0.18429945,  0.1839649 ,  0.14

In [58]:
# 상위 5%에 해당하는 index 얻기
np.sort(large_arr)[::-1][int(0.05) * len(large_arr)]

2.447067921137631

In [60]:
# unique 중복된 값 제거