In [4]:
# 파이썬 라이브러리인 numpy부터 import
import numpy as np

In [5]:
arr2d = np.array(([1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]))

In [12]:
# [행, 열]에 대한 array 가져오기 / 0부터 시작 / slicing할 때는 시작부터 끝-1까지
arr2d[:, 3] 

array([ 4,  8, 12, 16])

In [8]:
arr2d[:, :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [11]:
# 행의 index, 열의 index / 0부터 시작
arr2d[3,2]

15

In [13]:
arr2d[:2, 1:3] = 0

In [14]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
# boolean 인덱싱
names = np.array(["Charles", "Hayoung", "Kilho", "leo"])
# random한 수로 구성된 array 생성 / ()크기 
data = np.random.randn(4,4) 

In [17]:
names

array(['Charles', 'Hayoung', 'Kilho', 'leo'], dtype='<U7')

In [19]:
data
# 각 행은 names에 대응 됨

array([[ 2.50409366,  1.28073549, -1.18631456, -1.28970554],
       [ 1.33217499, -1.24620573,  0.97000456,  0.57938504],
       [-0.5675512 ,  0.61417393, -0.25337677, -0.90845111],
       [-1.24988358,  1.22840591,  1.66949185,  0.23866213]])

In [21]:
names == "Charles"
#값이 charles인 경우 true, 아니면 false / 불리언 array / 다른 array를 indexing하는데 사용 됨

array([ True, False, False, False])

In [34]:
# Charles인 경우의 행이 추출
data[names == "Charles", :]

array([[ 2.50409366,  1.28073549, -1.18631456, -1.28970554]])

In [24]:
# 기존 charles와 kilho에 해당하는 위치에 대응되는 행을 가져온다
data[(names == "Charles") | (names == "Kilho"), :]

array([[ 2.50409366,  1.28073549, -1.18631456, -1.28970554],
       [-0.5675512 ,  0.61417393, -0.25337677, -0.90845111]])

In [27]:
# 행, 렬
data[:,3]

array([-1.28970554,  0.57938504, -0.90845111,  0.23866213])

In [29]:
# 열 <0 인 부분 불리언
data[:,3] < 0

array([ True, False,  True, False])

In [33]:
data[data[:,3] < 0, :] 
# 0보다 작은 부분의 행을 다 추출한다

array([[ 2.50409366,  1.28073549, -1.18631456, -1.28970554],
       [-0.5675512 ,  0.61417393, -0.25337677, -0.90845111]])